### ISSUE TITLE
Fix mock server

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-blockchain#951] opened 2021-03-01 10:20 UTC
Investigate logs and Kibana dashboard for further understanding on the cause and solution (testnet).

**Comment by goshawk-3** [comment] 2021-03-01 15:20
Consensus seems to be properly running for 5 of the 6 nodes of the network. Only `dusk-9` seems to be not syncing since `49889` round

```Network height```

https://kibana.monitoring.dusk.network/app/metrics/explorer?metricsExplorer=(chartOptions:(stack:!f,type:line,yAxisMode:fromZero),options:(aggregation:avg,groupBy:!(agent.hostname),metrics:!((aggregation:avg,color:color0,field:prometheus.dusk_block.value)),source:url),timerange:(from:now-24h,interval:%3E%3D10s,to:now))&waffleFilter=(expression:%27%27,kind:kuery)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,view:map)&waffleTime=(currentTime:1610530486594,isAutoReloading:!f)

```Block time:```

https://kibana.monitoring.dusk.network/app/metrics/explorer?metricsExplorer=(chartOptions:(stack:!f,type:line,yAxisMode:fromZero),options:(aggregation:avg,groupBy:!(agent.hostname),metrics:!((aggregation:avg,color:color0,field:prometheus.dusk_effective_block_time.value)),source:url),timerange:(from:now-24h,interval:%3E%3D10s,to:now))&waffleFilter=(expression:%27%27,kind:kuery)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,view:map)&waffleTime=(currentTime:1610530486594,isAutoReloading:!f)

**Comment by goshawk-3** [comment] 2021-03-02 08:33
Moving this into `Parked` for monitoring purpose.

**Comment by autholykos** [comment] 2021-03-02 09:48
From @jules comment "On the DevNet, a node was observed getting stuck after around 43,000 blocks. The cause of this seemed to have been a context deadline being exceeded by the ExecuteStateTransition function. After checking the list of active processes, it looked like the mock rusk server had been restarted, as the uptime was vastly different from the node's uptime. The cause of the crash will need to be investigated and fixed in order to promote a stable DevNet."

**Comment by julesdesmit** [comment] 2021-03-02 09:51
The problem repeated itself on another run. Logs state this:

```
{"count":7,"level":"debug","msg":"collected agreement","process":"agreement","quorum":6,"round":49890,"step":3,"time":"2021-03-01T13:54:40+01:00"}
{"height":49890,"level":"info","msg":"calling ExecuteStateTransitionFunction","process":"accept block","provisioners":7,"time":"2021-03-01T13:54:40+01:00"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","height":49890,"level":"error","msg":"Error in executing the state transition","process":"accept block","time":"2021-03-01T13:54:52+01:00"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"error","msg":"failed to process message","process":"readloop","time":"2021-03-01T13:54:52+01:00"}
{"curr":49889,"level":"debug","msg":"Start syncing","process":"chain","target":49891,"time":"2021-03-01T13:54:52+01:00","tip":49891}
```

**Comment by julesdesmit** [comment] 2021-03-02 10:25
After further discussion with @goshawk-3, it does indeed seem that the mock rusk server has not crashed. The launch date is the exact same as the launch date of the node.

I've attached `delve`, but to no avail so far. It mostly seems like it just has the standard GRPC server goroutines running, with nothing in particular hanging.

**Closed** 2021-03-03 09:35 UTC
Labels: need:investigation, team:WebTech
