### ISSUE TITLE
Mismatch of Header round and step in score creation panic

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#584] opened 2020-07-18 09:24 UTC
```
"mismatch of Header round and step in score creation. ScoreProposal has a different Round and Step (19, 1) than the Coordinator (19, 2)" process="candidate generator"
```

**Comment by ggoranov** [comment] 2020-07-20 07:44
This might be result of a race condition: https://github.com/dusk-network/dusk-blockchain/issues/585

**Comment by autholykos** [comment] 2020-09-08 10:15
Closing as duplicate of #649

**Closed by autholykos** 2020-09-08 10:15 UTC
Labels: type:bug
