### ISSUE TITLE
Replace current UTXO model for Phoenix

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#298] opened 2020-03-02 10:15 UTC
This entails that the wallet no longer does its own generation of transactions, but instead reaches out to a 'phoenix server' process (over gRPC), to generate the data. The `Transactor` should be deprecated, and `dusk-wallet` could become a gRPC client.

**Comment by autholykos** [comment] 2020-04-22 16:44
closing as it is a duplicate of #411

**Closed by autholykos** 2020-04-22 16:44 UTC
Labels: area:tx, status:duplicate, type:IPC
