### ISSUE TITLE
Clarify the effects of `startprovisioner`

### ISSUE THREAD

**Issue by Rigorously** [dusk-network/dusk-blockchain#7] opened 2019-07-28 22:16 UTC
It is not so intuitive that you can execute startprovisioner without staking. According to the documentation it is necessary to stake.

```"stake": Stake a given amount of DUSK, to allow participation as a provisioner in consensus. Make sure to use the sync command first.```

What is actually happening when you run startprovisioner without staking?

Is it a deliberate choice to let users sync manually instead of syncing automatically? What is the risk of staking without syncing?

**Comment by julesdesmit** [comment] 2019-08-05 09:52
Hey! You're right, it is a bit convoluted from a docs perspective, so allow me to clarify:

When you type `startprovisioner` into the console, it starts up all of the codebase components needed to be able to function as a provisioner. The provisioner components do not need to know about any specific stake - this is because the consensus keypairs are deterministically generated from the wallet seed on startup, and passed to those components. Since the running stakes are managed by a `Committee` object, the components can infer themselves whenever it is appropriate to vote. This is in contrast to the block generation components, which need to have specific values from a bidding transaction in order to generate the bids.

That said, the provisioner components will not actually start their activities until a seperate component discovers a stake belonging to the node in any incoming blocks. This component will supply a starting round to the provisioner components, who will then begin their duties. So, when `startprovisioner` is ran without any active stake, the components will serve to relay consensus messages, and they will wait for a starting round to be propagated inside of the node. Therefore, it is possible to run startprovisioner without staking, and then stake later on.

Let me know if that is clear - I am happy to clarify anything. In the meantime I will reword the issue to adjust documentation for this to be clearer, and possibly open another issue for this point:

> Is it a deliberate choice to let users sync manually instead of syncing automatically? What is the risk of staking without syncing?

No guards are established for this. It is fine to stake without syncing (as the stake is included in a block that's appended to the current tip), though running `startprovisioner` after staking while syncing could lead to some unexpected behaviour. I think it could lead to a node starting on an obsolete round, which is undesirable as it would get stuck. I would need to investigate it though.

**Comment by julesdesmit** [comment] 2019-08-31 09:36
Closing this, as #27 makes this issue obsolete.

**Closed by julesdesmit** 2019-08-31 09:36 UTC
Labels: documentation
